In [1]:
import wagen.caltopo_io as cti
import wagen.timeline as tl
import pandas as pd
from pprint import pp
import datetime as dt

In [2]:
cfg = dict(
    start_time=dt.datetime.fromisoformat('2025-09-23'),
    morning_daylight=1.5,
    evening_daylight=2.0,
    include_dt=False)

# To Little Colorado River (LCR). Rafting option.
Optional 8 mile packraft from LCR to above Tanner Rapid.
The Colorado river in GC flows and average speed of about 4 mph.

In [3]:
raft_df, trip = cti.travelplan_multi_csv(csvfname='~/Downloads/travelplan.GC-LCR-raft.csv')
display(trip)
display(raft_df.round(1))

Wrote Excel version of dataframe to ~/Downloads/travelplan.GC-LCR-raft.xlsx

{'start_latlon': [36.03268, -111.85245], 'start_elevation': 7366}

,day,eod,segment,waypoint,trip_leg,elevation,aeg,ael,distance,duration,break_time,notes,hours,pace
0,1,False,a Tan dwn,Start,1,7366,0,0,0.0,0,0,,0.0,0
1,1,False,a Tan dwn,End,2,2718,405,-5052,6.6,284,0,,4.7,42
2,1,False,b Tan2Pal,Start,3,2722,0,0,0.0,0,0,,0.0,0
3,1,True,b Tan2Pal,camp,4,2700,253,-275,3.0,69,0,,1.2,23
4,1,True,b Tan2Pal,portage in,5,2704,4,0,0.1,1,0,,0.0,12
5,1,True,b Tan2Pal,End,6,2713,9,0,0.1,3,0,,0.0,21
6,1,True,c Pal2LCR,EOD1,EOD1,2713,0,0,0.0,0,0,,0.0,0
7,2,False,c Pal2LCR,Start,7,2710,0,0,0.0,0,0,,0.0,0
8,2,False,c Pal2LCR,viewpoint,8,2999,717,-428,2.2,86,0,Temple Butte,1.4,39
9,2,False,c Pal2LCR,LCR view?,9,2820,387,-567,2.3,76,0,,1.3,32
10,2,False,c Pal2LCR,End,10,2700,76,-195,1.1,28,0,,0.5,25
11,2,False,da RABT 1,Start,11,2700,0,0,0.0,0,0,,0.0,0
12,2,False,da RABT 1,Carbon ck,12,2700,23,-23,3.7,52,0,riffle,0.9,14
13,2,False,da RABT 1,portage out,13,2700,0,0,0.8,11,0,OPTIONAL,0.2,13
14,2,False,da RABT 1,Lava cyn Rapid,14,2700,0,0,0.1,1,0,"GC class 4, drop 4 ft\nRM 65.9",0.0,11
15,2,False,da RABT 1,portage in,15,2700,0,0,0.0,1,0,,0.0,26
16,2,False,da RABT 1,End,16,2700,0,0,0.0,1,0,,0.0,22
17,2,False,ea RABT 2,Start,17,2700,0,0,0.0,0,0,,0.0,0
18,2,False,ea RABT 2,Espejo ck,18,2684,13,-29,1.4,20,0,,0.3,14
19,2,False,ea RABT 2,Comanche ck,19,2684,0,0,0.3,4,0,,0.1,15
20,2,False,ea RABT 2,take-out,20,2683,31,-32,1.1,24,0,,0.4,22
21,2,False,ea RABT 2,End,21,2722,39,0,0.1,14,0,,0.2,152
22,2,False,f Tan camp,Start,22,2720,0,0,0.0,0,0,,0.0,0
23,2,True,f Tan camp,camp,23,2690,0,-29,0.1,3,0,,0.0,27
24,2,True,f Tan camp,End,24,2684,0,-7,0.0,1,0,,0.0,20
25,2,True,g Tan up,EOD2,EOD2,2684,0,0,0.0,0,0,,0.0,0
26,3,False,g Tan up,Start,25,2698,0,0,0.0,0,0,,0.0,0
27,3,True,g Tan up,car,26,7392,5106,-412,6.8,389,0,,6.5,57
28,3,True,g Tan up,End,27,7392,0,0,0.0,1,0,,0.0,29
29,3,True,g Tan up,EOD3,EOD3,7392,0,0,0.0,0,0,,0.0,0

## Timeline

In [4]:
times_df, meta = tl.timeline(raft_df, trip, **cfg)

print(trip)
print(meta)
with pd.option_context("display.max_columns", None):
    display(times_df.round(1))

{'start_latlon': [36.03268, -111.85245], 'start_elevation': 7366}
{'first_date': '2025-09-23', 'day_start_time': '07:21', 'twilight': '2025-09-24T05:51:51-07:00', 'sunrise': '2025-09-24T06:16:06-07:00', 'sunset': '2025-09-23T18:23:49-07:00', 'start_latlon': [36.03268, -111.85245], 'start_elevation': 7366, 'morning_daylight': 1.5, 'evening_daylight': 2.0, 'tzid': 'America/Phoenix', 'eod_times': {1: datetime.time(13, 14), 2: datetime.time(12, 42), 3: datetime.time(13, 50)}}

,date,time,day,waypoint,distance,aeg,ael,spent_time,duration,break_time,elevation,hours,pace,segment
0,2025-09-23,07:21,1,Start,0.0,0,0,0.0,0,0,7366,0.0,0,a Tan dwn
1,2025-09-23,12:05,1,End,6.6,405,-5052,4.7,284,0,2718,4.7,42,a Tan dwn
2,2025-09-23,12:05,1,Start,0.0,0,0,4.7,0,0,2722,0.0,0,b Tan2Pal
3,2025-09-23,13:14,1,camp,3.0,253,-275,5.9,69,0,2700,1.2,23,b Tan2Pal
4,2025-09-23,13:15,1,portage in,0.1,4,0,5.9,1,0,2704,0.0,12,b Tan2Pal
5,2025-09-23,13:18,1,End,0.1,9,0,6.0,3,0,2713,0.0,21,b Tan2Pal
6,2025-09-23,13:18,1,EOD1,0.0,0,0,6.0,0,0,2713,0.0,0,c Pal2LCR
7,2025-09-24,07:21,2,Start,0.0,0,0,0.0,0,0,2710,0.0,0,c Pal2LCR
8,2025-09-24,08:47,2,viewpoint,2.2,717,-428,1.4,86,0,2999,1.4,39,c Pal2LCR
9,2025-09-24,10:03,2,LCR view?,2.3,387,-567,2.7,76,0,2820,1.3,32,c Pal2LCR
10,2025-09-24,10:31,2,End,1.1,76,-195,3.2,28,0,2700,0.5,25,c Pal2LCR
11,2025-09-24,10:31,2,Start,0.0,0,0,3.2,0,0,2700,0.0,0,da RABT 1
12,2025-09-24,11:23,2,Carbon ck,3.7,23,-23,4.0,52,0,2700,0.9,14,da RABT 1
13,2025-09-24,11:34,2,portage out,0.8,0,0,4.2,11,0,2700,0.2,13,da RABT 1
14,2025-09-24,11:35,2,Lava cyn Rapid,0.1,0,0,4.2,1,0,2700,0.0,11,da RABT 1
15,2025-09-24,11:36,2,portage in,0.0,0,0,4.2,1,0,2700,0.0,26,da RABT 1
16,2025-09-24,11:37,2,End,0.0,0,0,4.3,1,0,2700,0.0,22,da RABT 1
17,2025-09-24,11:37,2,Start,0.0,0,0,4.3,0,0,2700,0.0,0,ea RABT 2
18,2025-09-24,11:57,2,Espejo ck,1.4,13,-29,4.6,20,0,2684,0.3,14,ea RABT 2
19,2025-09-24,12:01,2,Comanche ck,0.3,0,0,4.7,4,0,2684,0.1,15,ea RABT 2
20,2025-09-24,12:25,2,take-out,1.1,31,-32,5.1,24,0,2683,0.4,22,ea RABT 2
21,2025-09-24,12:39,2,End,0.1,39,0,5.3,14,0,2722,0.2,152,ea RABT 2
22,2025-09-24,12:39,2,Start,0.0,0,0,5.3,0,0,2720,0.0,0,f Tan camp
23,2025-09-24,12:42,2,camp,0.1,0,-29,5.4,3,0,2690,0.0,27,f Tan camp
24,2025-09-24,12:43,2,End,0.0,0,-7,5.4,1,0,2684,0.0,20,f Tan camp
25,2025-09-24,12:43,2,EOD2,0.0,0,0,5.4,0,0,2684,0.0,0,g Tan up
26,2025-09-25,07:21,3,Start,0.0,0,0,0.0,0,0,2698,0.0,0,g Tan up
27,2025-09-25,13:50,3,car,6.8,5106,-412,6.5,389,0,7392,6.5,57,g Tan up
28,2025-09-25,13:51,3,End,0.0,0,0,6.5,1,0,7392,0.0,29,g Tan up
29,2025-09-25,13:51,3,EOD3,0.0,0,0,6.5,0,0,7392,0.0,0,g Tan up

# To Little Colorado River (LCR). NO RAFT option.

In [5]:
df, trip, meta = tl.trip_timeline(csvfname='~/Downloads/travelplan.GC-LCR-noraft.csv', **cfg)
display(meta)
display(df.round(1))

Wrote Excel version of dataframe to ~/Downloads/travelplan.GC-LCR-noraft.xlsx

{'first_date': '2025-09-23',
 'day_start_time': '07:21',
 'twilight': '2025-09-24T05:51:51-07:00',
 'sunrise': '2025-09-24T06:16:06-07:00',
 'sunset': '2025-09-23T18:23:49-07:00',
 'start_latlon': [36.03268, -111.85245],
 'start_elevation': 7366,
 'morning_daylight': 1.5,
 'evening_daylight': 2.0,
 'tzid': 'America/Phoenix',
 'eod_times': {1: datetime.time(13, 14),
  2: datetime.time(13, 54),
  3: datetime.time(13, 50)}}

,date,time,day,waypoint,distance,aeg,ael,spent_time,duration,break_time,elevation,hours,pace,segment
0,2025-09-23,07:21,1,Start,0.0,0,0,0.0,0,0,7366,0.0,0,a Tan dwn
1,2025-09-23,12:05,1,End,6.6,405,-5052,4.7,284,0,2718,4.7,42,a Tan dwn
2,2025-09-23,12:05,1,Start,0.0,0,0,4.7,0,0,2722,0.0,0,b Tan2Pal
3,2025-09-23,13:14,1,camp,3.0,253,-275,5.9,69,0,2700,1.2,23,b Tan2Pal
4,2025-09-23,13:18,1,End,0.2,13,0,6.0,4,0,2713,0.1,18,b Tan2Pal
5,2025-09-23,13:18,1,EOD1,0.0,0,0,6.0,0,0,2713,0.0,0,c Pal2LCR
6,2025-09-24,07:21,2,Start,0.0,0,0,0.0,0,0,2710,0.0,0,c Pal2LCR
7,2025-09-24,08:47,2,viewpoint,2.2,717,-428,1.4,86,0,2999,1.4,39,c Pal2LCR
8,2025-09-24,10:03,2,LCR view?,2.3,387,-567,2.7,76,0,2820,1.3,32,c Pal2LCR
9,2025-09-24,10:31,2,End,1.1,76,-195,3.2,28,0,2700,0.5,25,c Pal2LCR
10,2025-09-24,10:31,2,Start,0.0,0,0,3.2,0,0,2700,0.0,0,d LCR2Pal
11,2025-09-24,11:02,2,LCR view?,1.1,200,-84,3.7,31,0,2816,0.5,28,d LCR2Pal
12,2025-09-24,12:25,2,viewpoint,2.3,590,-404,5.1,83,0,3002,1.4,35,d LCR2Pal
13,2025-09-24,13:47,2,End,2.2,436,-728,6.4,82,0,2710,1.4,37,d LCR2Pal
14,2025-09-24,13:47,2,Start,0.0,0,0,6.4,0,0,2717,0.0,0,e Pal2Tan
15,2025-09-24,13:54,2,camp,0.4,0,-20,6.6,7,0,2700,0.1,18,e Pal2Tan
16,2025-09-24,15:03,2,take-out,3.0,272,-234,7.7,69,0,2738,1.2,23,e Pal2Tan
17,2025-09-24,15:08,2,End,0.2,0,-54,7.8,5,0,2685,0.1,24,e Pal2Tan
18,2025-09-24,15:08,2,EOD2,0.0,0,0,7.8,0,0,2685,0.0,0,f Tan up
19,2025-09-25,07:21,3,Start,0.0,0,0,0.0,0,0,2698,0.0,0,f Tan up
20,2025-09-25,13:50,3,car,6.8,5106,-412,6.5,389,0,7392,6.5,57,f Tan up
21,2025-09-25,13:51,3,End,0.0,0,0,6.5,1,0,7392,0.0,29,f Tan up
22,2025-09-25,13:51,3,EOD3,0.0,0,0,6.5,0,0,7392,0.0,0,f Tan up